### ISSUE TITLE
SOMETIMES CRASHES AFTER PICKING IMAGE FROM GALLERY

### ISSUE THREAD

**Issue by Lorengamboa** [react-native-image-picker/react-native-image-picker#1389]
# Bug report

## Summary
Im making an app where I pick images from gallery and store them into redux persist store and eventually display them into image list.
The issue comes up when I have already add a certain amount of pictures and after reaching that limit the app crashes and reset after adding a new picture.
I have check and its not memory usage issue or something related.

## Environment info

ANDROID LOGCAT
--------------------
2020-07-04 03:49:46.649 11442-11442/? E/m.tierlistmake: Unknown bits set in runtime_flags: 0x8000
2020-07-04 03:49:46.695 11442-11442/? E/libc: Access denied finding property "runtime.mmitest.isrunning"
2020-07-04 03:49:47.256 11442-11487/com.tierlistmaker E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@a19b67e

Library version :2.3.1

## Steps to reproduce
1 - Go to gallery pick
2 - Select image

Describe what you expected to happen:

1. Go back to aplication after selecting the image from gallery

**Comment by PatricioBedregal** [comment]
This happens to me too, sometimes after picking the image randomly crashes

**Comment by Luckygirlllll** [comment]
Is there any solution for this problem? I have the same problem with Android.

**Comment by brunogonncalves** [comment]
I have this problem too

**Comment by darron1217** [comment]
I found the clue from error message
`Caused by: java.lang.IllegalArgumentException: Invalid column latitude`

Here's my error log
```
2020-12-29 19:15:57.853 31345-31345/com.enre.staff E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.enre.staff, PID: 31345
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/65/ORIGINAL/NONE/1855835881 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F65/ORIGINAL/NONE/1855835881} }} to activity {com.enre.staff/com.enre.staff.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.imagepicker.Utils.getVideoResponseMap(Utils.java:338)
        at com.imagepicker.ImagePickerModule.onVideoObtained(ImagePickerModule.java:138)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:169)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```

@ravirajn22 would you re-open this issue?

**Comment by sekizlipenguen** [comment]
> I found the clue from error message
> `Caused by: java.lang.IllegalArgumentException: Invalid column latitude`
> 
> Here's my error log
> 
> ```
> 2020-12-29 19:15:57.853 31345-31345/com.enre.staff E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.enre.staff, PID: 31345
>     java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/65/ORIGINAL/NONE/1855835881 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F65/ORIGINAL/NONE/1855835881} }} to activity {com.enre.staff/com.enre.staff.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>      Caused by: java.lang.IllegalArgumentException: Invalid column latitude
>         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
>         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
>         at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
>         at android.content.ContentResolver.query(ContentResolver.java:944)
>         at android.content.ContentResolver.query(ContentResolver.java:880)
>         at android.content.ContentResolver.query(ContentResolver.java:836)
>         at com.imagepicker.Utils.getVideoResponseMap(Utils.java:338)
>         at com.imagepicker.ImagePickerModule.onVideoObtained(ImagePickerModule.java:138)
>         at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:169)
>         at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
>         at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
>         at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
>         at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
>         at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
>         at android.app.Activity.dispatchActivityResult(Activity.java:8110)
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
>         at android.os.Handler.dispatchMessage(Handler.java:107) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.app.ActivityThread.main(ActivityThread.java:7356) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
> ```
> 
> @ravirajn22 would you re-open this issue?

+1
