### ISSUE TITLE
crash on android launchImageLibrary when WRITE_EXTERNAL_STORAGE denied and resize

### ISSUE THREAD

**Issue by CastixGitHub** [react-native-image-picker/react-native-image-picker#1499]
### Description
App crashes, no logs from react native
instead, from `adb logcat`
```
11-18 15:01:27.119 10381 10381 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/34633 flg=0x1 }} to activity {com.PanDi/com.pandi.MainActivity}: java.lang.NullPointerException: uri
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: Caused by: java.lang.NullPointerException: uri
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:786)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:753)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:711)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.imagepicker.Utils.getResponseMap(Utils.java:308)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.onImageObtained(ImagePickerModule.java:130)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:161)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7462)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
11-18 15:01:27.119 10381 10381 E AndroidRuntime: 	... 11 more
11-18 15:01:27.129  2421  2728 D SurfaceFlinger: duplicate layer name: changing Surface(name=345d5db StatusBar)/@0xc3843f1 - animation-leash to Surface(name=345d5db StatusBar)/@0xc3843f1 - animation-leash#1
11-18 15:01:27.135  3392  3808 W ActivityManager:   Force finishing activity com.PanDi/com.pandi.MainActivity
11-18 15:01:27.148  3392  5390 I OpenGLRenderer: Initialized EGL, version 1.4
11-18 15:01:27.148  3392  5390 D OpenGLRenderer: Swap behavior 2
11-18 15:01:27.152 10381 10381 I Process : Sending signal. PID: 10381 SIG: 9
11-18 15:01:27.172  3392  5390 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1218x934]-format:1
11-18 15:01:27.287  3392  3480 I WindowManager: WIN DEATH: Window{a20684c u0 com.PanDi/com.pandi.MainActivity}
11-18 15:01:27.288  3392  5518 I ActivityManager: Process com.PanDi (pid 10381) has died: fore TOP 
```

### How to repeat issue and example
* lauch `launchImageLibrary` and negate the permission request
* pick an image from the library
* the app crashes

### Solution

What needs to be done to address this issue? 
The app should not crash, it should answer with a response that has errorCode: permission

### Additional Information

```
    Image Picker version: ├─ react-native-image-picker@3.0.0-vnext.4
    React Native version: ├─ react-native@0.63.2
    Platform: Android, not tested on ios
    Development Operating System: Linux
```

**Comment by ravirajn22** [comment]
This library does not require any permissions unless you use `saveToPhotos`, check docs for more info.

Tell your test device info to debug.

**Comment by CastixGitHub** [comment]
> This library does not require any permissions unless you use `saveToPhotos`, check docs for more info.
well if, that option is given, the library could just check (without asking) the permission, avoiding the crash (just a matter of application code style, and the documented errorCode: permission makes you think that way even more)
> 
> Tell your test device info to debug.
SM-G903F with android 9 (lineage 16.0)

thank you

**Comment by ravirajn22** [comment]
> well if, that option is given, the library could just check (without asking) the permission, avoiding the crash (just a matter of application code style, and the documented errorCode: permission makes you think that way even more)

Yes when you set `saveToPhotos` it will check for permission(does not ask), and  return if permission is not satisfied. This is how the library works.

**Comment by CastixGitHub** [comment]
ok, then, lauch launchImageLibrary without permission, it will crash

**Comment by ravirajn22** [comment]
If you have any other device, can you test it on that. Because I cant reproduce your issue in my device. I need to know if its device specific issue.

**Comment by herbertvuijk** [comment]
Having the same issue.

**Comment by CastixGitHub** [comment]
@herbertvuijk can you paste the traceback printed here from https://github.com/react-native-image-picker/react-native-image-picker/blob/main/android/src/main/java/com/imagepicker/Utils.java#L183

The best approach would be to check the write permission only if a resize should be applied, even before launching the gallery intent; if resize will not be applied, then there is no need for asking the permission.

anyway we workarounded this in our app by checking the permission before calling the library

**Comment by ravirajn22** [comment]
WRITE_EXTERNAL_STORAGE is only required when you use `saveToPhotos: true` in all other cases its not required. If you can add more details it help to diagnose.

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here with details I am happy to fix it.
