### ISSUE TITLE
[🐛] Unable to resolve module `./internal/nativeInterface`

### ISSUE THREAD

**Issue by grkemtneri** [react-native-image-picker/react-native-image-picker#1545]
### Description

I update  2.3.4 to 3.1.1 react native image picker but ı get Unable to resolve module

### Code 

```
import { launchImageLibrary } from 'react-native-image-picker';
const fromLibrary = () => {
  launchImageLibrary(
    {
      mediaType: 'photo',
      includeBase64: true,
    },
    (response) => {
      setImage(response);
    },
  );
};
```

```
`error: Error: Unable to resolve module `./internal/nativeInterface` from `node_modules\react-native-image-picker\src\index.ts`:

None of these files exist:
  * node_modules\react-native-image-picker\src\internal\nativeInterface(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-image-picker\src\internal\nativeInterface\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Gorkem\Desktop\workspace\CampainApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)`
```

### Additional Information

- Image Picker version:3.1.1
- React Native version:0.63.3
- Platform: Android
- Development Operating System: Windows

**Comment by Johan-dutoit** [comment]
Restart your packager/bundler and rebuild your application.

**Comment by grkemtneri** [comment]
I tried remove node modes then npm install ı removed app/build and rerun project . nothing happened

**Comment by Johan-dutoit** [comment]
`./internal/nativeInterface` doesn't exist in v3.  There is clearly a caching issue somewhere.

**Comment by patelhari** [comment]
Same error, any solution?

**Comment by grkemtneri** [comment]
did you try `npm start --reset-cache or react-native start --reset-cache` ?

**Comment by patelhari** [comment]
Yes, still not solve.
