### ISSUE TITLE
Can't get the actual path of image where it is stored in my internal storage[🌟] 

### ISSUE THREAD

**Issue by sameerahmed56** [react-native-image-picker/react-native-image-picker#1580]
### Description

Explain the feature request in as much detail as possible.

### Proposed Solution

What needs to be done to make it happen?

### Test Solution

How would we test & validate the feature?

**Comment by yamavol** [comment]
I also found this issue during my Android App development.
Currently, the library seems to create a new (resized) image from the selected image.
It might be nice if there is a way to access the image through fileURI, not contentURI.

https://github.com/react-native-image-picker/react-native-image-picker/blob/4bba2470452cd91a16e53049ab8c965b111acbb6/android/src/main/java/com/imagepicker/ImagePickerModule.java#L133-L134

**Comment by ravirajn22** [comment]
@sameerahmed56 what is the problem in using the returned uri on android and ios? Elaborate on the problem you'r facing.

**Comment by efstathiosntonas** [comment]
this came into crashlytics today:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/963/ORIGINAL/NONE/image/jpeg/1882044403 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F963/ORIGINAL/NONE/image%2Fjpeg/1882044403} }} to activity {com.XXX/com.XXXX.MainActivity}: java.lang.NullPointerException: uri
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4544)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4586)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6991)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

i'm using `3.2.1`

**Comment by dllz** [comment]
Hi, I am having this problem as well. I feel like making another issue is pointless. My issue is that the tesseract library (https://github.com/jonathanpalma/react-native-tesseract-ocr) I am using to do OCR cannot handle the in app path, I get a file not found exception, when passing in the path to internal storage manually the issue is resolved and the library works.

**Comment by ravirajn22** [comment]
Now latest version provides file uri to images. I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
