### ISSUE TITLE
[🐛] The camera application crash after confirming the photo 

### ISSUE THREAD

**Issue by marcosdourado** [react-native-image-picker/react-native-image-picker#1637]
### Description

The camera application stops working after confirming the photo taken.
I have two camera apps on my phone, I had a problem with:

org.codeaurora.snapcam

With the native app of POCO F1 it worked properly, users with Samsung also presented problems.

I was able to find some information in the debug:

`[ERROR][JPEG   ] camxjpegexifparams.cpp:1113 GetEXIFUserComment()  GetEXIFUserComment`

`Expect face scores and rectangles to be non-null`

```
Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
java.io.IOException: Invalid byte order: ffff8950
	at android.media.ExifInterface.readByteOrder(ExifInterface.java:3128)
	at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
	at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
	at android.media.ExifInterface.<init>(ExifInterface.java:1449)
	at com.bumptech.glide.load.resource.bitmap.p.a(SourceFile:3)
	at com.bumptech.glide.load.b.a(SourceFile:12)
	at com.bumptech.glide.load.resource.bitmap.l.a(SourceFile:22)
	at com.bumptech.glide.load.resource.bitmap.l.a(SourceFile:11)
	at com.bumptech.glide.load.resource.bitmap.l.a(SourceFile:1)
	at com.bumptech.glide.load.resource.bitmap.f.a(SourceFile:5)
	at com.bumptech.glide.load.resource.bitmap.f.a(SourceFile:1)
	at com.bumptech.glide.load.engine.k.a(SourceFile:12)
	at com.bumptech.glide.load.engine.k.a(SourceFile:5)
	at com.bumptech.glide.load.engine.k.a(SourceFile:1)
	at com.bumptech.glide.load.engine.B.a(SourceFile:6)
	at com.bumptech.glide.load.engine.B.a(SourceFile:2)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:70)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:58)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:53)
	at com.bumptech.glide.load.engine.DecodeJob.e(SourceFile:3)
	at com.bumptech.glide.load.engine.DecodeJob.a(SourceFile:41)
	at com.bumptech.glide.load.engine.e.a(SourceFile:20)
	at com.bumptech.glide.load.b.f$a.a(SourceFile:2)
	at com.bumptech.glide.load.engine.e.a(SourceFile:10)
	at com.bumptech.glide.load.engine.DecodeJob.l(SourceFile:4)
	at com.bumptech.glide.load.engine.DecodeJob.m(SourceFile:7)
	at com.bumptech.glide.load.engine.DecodeJob.run(SourceFile:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	at com.bumptech.glide.load.engine.c.a.run(SourceFile:8)

```

### How to repeat issue and example

- Use launchCamera;
- Confirm the photo.

 
### Additional Information

- Image Picker version: 3.2.1
- React Native version: 0.64.0
- Platform: Android  
- Development Operating System: Linux
\

**Comment by alex-steinberg** [comment]
What was the solution here @marcosdourado ?
