### ISSUE TITLE
[🐛] Back camera crashed after capturing image and while return to the app.

### ISSUE THREAD

**Issue by mohandarsi** [react-native-image-picker/react-native-image-picker#1929]
### Description

After Capturing the image from the back camera application crashes with the following call stack. 
When I use the front camera to capture the image or gallery to select the image the same functionality works as expected.
On the simulator, no crashes were observed.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mybook/com.myrbook.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6651)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:297)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
at android.app.Activity.performCreate(Activity.java:7088)
at android.app.Activity.performCreate(Activity.java:7079)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
... 9 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
```

### How to repeat issue and example

```
const options: CameraOptions = {
	mediaType: 'photo',
	maxWidth: 700,
	maxHeight: 400,
	quality: 0.7,
	includeBase64: true
};
const handleImagePickerResponse = (response: ImagePickerResponse) => { 
....
}
launchCamera(options, response => handleImagePickerResponse(response));
```

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 4.7.0/4.7.3
- React Native version: 0.66.4/0.67.1
- Platform: Android (8.1.0, Redmi note 5)
- Development Operating System:  Windows

**Comment by SomnathKadam** [comment]
same issue

**Comment by abdulqadir-jugnu** [comment]
Same issue on some devices. Issue maybe due to low memory sometimes when device ram is full it kills the app in background as camera and image-picker is also itself an intent and opens new app

**Comment by salmanafzal775** [comment]
storageOptions: {
        skipBackup: true,
        path: 'images',
      },
Add this to your code. Hope it works for you

**Comment by pjcaro** [comment]
update?
