### ISSUE TITLE
[🐛] Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by dipendra-sharma** [react-native-image-picker/react-native-image-picker#1936]
### Description

Application Crash while picking Image. 
`Caused by java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
       at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:184)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
       at money.jupiter.MainActivity.onActivityResult(MainActivity.kt:47)
       at android.app.Activity.dispatchActivityResult(Activity.java:8113)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5037)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5085)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7581)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`

### How to repeat issue and example

- Not reproducible every-time. Seems Random crash being received.

### Additional Information

- Image Picker version: ^4.0.4
- React Native version: ^0.64.1
- Platform: Android
- Development Operating System: Mac OS
- Dev tools: Android Studio

**Comment by me294** [comment]
same issue !

**Comment by Johan-dutoit** [comment]
Can you replicate it with the example app?

**Comment by dipendra-sharma** [comment]
I'm not facing this issue always. Getting it on Crashlytics.

**Comment by me294** [comment]
I resolved the issue replace react-native-image-picker with react-native-image-crop-picker because lib handle loading when picking an image

**Comment by Mervsz** [comment]
facing same issue. crashing after selecting an image

**Comment by dipendra-sharma** [comment]
Any update on this issue?

**Comment by JairajJangleSLIOT** [comment]
Possible duplicate of https://github.com/react-native-image-picker/react-native-image-picker/issues/713

**Comment by cadu1** [comment]
It's happening with me when I tap multiple times on the button and I don't have the default gallery app defined! I've tried to apply a solution that I found in another issue but with no success (using ref).

```
...
  const handleSelectProfilePicture = () => {
    if (isPickerOpen.current) return;
    isPickerOpen.current = true;

    try {
      const imageResult = launchImageLibrary({ mediaType: 'photo' }, () => {
        isPickerOpen.current = false;
      });
    ...
  }
...
<TouchableOpacity
  activeOpacity={1.0}
  onPress={handleSelectProfilePicture}
>
...

```
![image](https://user-images.githubusercontent.com/7523685/160473220-72aa36cf-0063-4c7b-87fa-47f50ea15c72.png)

**Comment by yorickshan** [comment]
any updates?

**Comment by Fardeen-N** [comment]
Can anyone of you able to figure out what's causing this or do we have to use alternative library 
any suggestion?
