### ISSUE TITLE
[🐛] Android crash if height/width not given 

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-image-picker/react-native-image-picker#2011]
### Description
On Android, if maxHeight or maxWidth are not given, launchCamera or library will just crash. On IOS, it just gives the original image instead of resizing as usual.
 

### How to repeat issue and example

```
const result = await launchCamera({
        mediaType: 'photo',
        maxWidth: quality ? quality : undefined,
        maxHeight: quality ? quality : undefined,
        quality: PHOTO_JPEG_MAP[photoQuality] / 100,
        includeBase64: false,
        includeExtra: false,
        selectionLimit: 1,
        presentationStyle: 'currentContext',
      });
```

```
com.facebook.react.bridge.NoSuchKeyException: maxHeight
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:157)
        at com.imagepicker.Options.<init>(Options.java:36)
        at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:72)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
```

### Solution
Handle the error on the Java native side.

### Additional Information

- Image Picker version: 4.8.6
- React Native version: 0.67.4

**Comment by Sachin926** [comment]
Hi @cristianoccazinsp this bug is not reproducible at my end right now, on the latest version (4.10.1) of this library, can you please verify this again on the latest version?
