### ISSUE TITLE
[🐛] Recording a video with launchCamera fails on Android SDK 33

### ISSUE THREAD

**Issue by timoteialbu** [react-native-image-picker/react-native-image-picker#2026]
### Description

Explain the bug in as much detail as possible
When trying to call the [launchCamera](https://github.com/react-native-image-picker/react-native-image-picker/blob/7490cc493737cd03f881cddeddbac28d43987534/src/index.ts#L15) method with the following options:
```
{
      saveToPhotos: true,
      mediaType: 'video',
}
```
on a Android 33 SDK phone/simulator it fails and returns
```
{
  didCancel: true
}
```

This is the error it shows in Android Studio:
```
FATAL EXCEPTION: main
Process: com.android.camera2, PID: 866
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:697)
	at com.android.camera.ShutterButton.performClick(ShutterButton.java:190)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### How to repeat issue and example

You can run the [example](https://github.com/react-native-image-picker/react-native-image-picker/tree/main/example) in this repo on a simulator running Android SDK 33 and it will fail with that error when you select the `Take Video` option.

### Solution

What needs to be done to address this issue?
I am not sure. I tried digging through the permissions and debugging it, but I was not able to find the issue.

### Additional Information

- Image Picker version: 4.10.0
- React Native version: 0.69.2
- Platform: Android
- Development Operating System: macOS
- Dev tools: Android Studio Chipmunk | 2021.2.1 Path 2

**Comment by DaneHoward** [comment]
Having the same issue. This feels like a critical bug so I hope it is in the next patch!

In Version:
Image Picker: 4.10.0
RN: 0.66.1
React: 17.0.2
Platform: Android & iOS
Dev OS: Windows 10 && Mac Mini M1
Android Studio Dolphin | 2021.3.1 Patch 1  && Xcode v 14.1

**Comment by DaneHoward** [comment]
Does anyone have any progress on this or a workaround? React-Native-Image-Picker gets 150k downloads a week but the video capture doesn't work? Help it make sense!

**Comment by alex-mironov** [comment]
+1

**Comment by cchaabane** [comment]
+1
- Image Picker version: 4.10.3
- React Native version: 0.70.6
- Platform: Android

**Comment by cchaabane** [comment]
@DaneHoward thanks for the reply. Makes sense since i'm working on an Emulator. 

Maybe worth mentioning for future investigations that on the Emulator, it fails even though the permission is granted.

**Comment by khushal87** [comment]
Hey, is there a fix for the issue? :)

**Comment by alimohsinz** [comment]
@khushal87 it is working in real device with release apk but not in emulator.
