### ISSUE TITLE
[🐛] app crashes when selecting an image (Android)

### ISSUE THREAD

**Issue by JaturongRocket** [react-native-image-picker/react-native-image-picker#2217]
I call launchImageLibrary for select image. If I cancel, unselect the image and press return. it's ok but if I press to select a picture, the app crash.

on iOS it's work.

Logcat:
`FATAL EXCEPTION: main
                                                                                                    Process: com.rocketpos, PID: 30578
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/44/ORIGINAL/NONE/image/png/215393063 flg=0x1 clip={text/uri-list {U(content)}} }} to activity {com.rocketpos/com.rocketpos.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5301)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5340)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
                                                                                                    	at com.reactnativesunmiprinter.SunmiScanModule$1.onActivityResult(SunmiScanModule.java:32)
                                                                                                    	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:338)
                                                                                                    	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:821)
                                                                                                    	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:133)
                                                                                                    	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8382)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5294)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5340) 
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) `

Lib : 7.0.0
RN : 0.71

**Comment by wezter96** [comment]
I have the same issue.

**Comment by kyadalu1** [comment]
https://www.youtube.com/watch?v=MrV4pXY1D-g

**Comment by vinaydrevankar** [comment]
Same issue. Is there any fix or workaround?

**Comment by vinaydrevankar** [comment]
Crash occurs because Uri.fromFile() will not work on Android 7.0+, with a targetSdkVersion of 24 or higher. I had to make below changes for it to work. Where comment line is the original code. Note: You need to get WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE permission for OS below Android API 31

ImagePickerModuleImpl.java
Line 98
  ```
Uri uri = FileProvider.getUriForFile(reactContext,
                reactContext.getPackageName() + ".provider"
                , file);
        fileUri = uri;
//        fileUri = Uri.fromFile(file);
```


Utils.java

Line 135
```
//        Uri toUri = Uri.fromFile(createFile(context, fileType));
        Uri toUri = FileProvider.getUriForFile(context,
                context.getPackageName() + ".provider"
                , createFile(context, fileType));

```

Line 216

```
Uri tempUri = FileProvider.getUriForFile(context,
                        context.getPackageName() + ".provider"
                        , file);

//                try (OutputStream os = context.getContentResolver().openOutputStream(Uri.fromFile(file))) {
                try (OutputStream os = context.getContentResolver().openOutputStream(tempUri)) {

```


Line 229


 ```
Uri resultUri = FileProvider.getUriForFile(context,
                        context.getPackageName() + ".provider"
                        , file);
                return resultUri;
//                return Uri.fromFile(file);

```
