### ISSUE TITLE
[🐛] App crash after taking photo with launchCamera on Android

### ISSUE THREAD

**Issue by plumest** [react-native-image-picker/react-native-image-picker#2343]
### Description
function launchCamera work perfectly on iOS but crash on Android.
function launchImageLibrary work well on both device.
this happen after I upgrading my SDK target to 34.

logcat
```bash
FATAL EXCEPTION: main
  Process: com.app, PID: 27985
  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13001, result=-1, data=Intent {  }} to activity {com.app/combineReducers.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5527)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5566)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8177)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
    at com.reactnativesunmiprinter.SunmiScanModule$2.onActivityResult(SunmiScanModule.java:53)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:375)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:809)
    at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:148)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:145)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
    at android.app.Activity.dispatchActivityResult(Activity.java:8943)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5520)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5566) 
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:205) 
    at android.os.Looper.loop(Looper.java:294) 
    at android.app.ActivityThread.main(ActivityThread.java:8177) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

### How to repeat issue and example

- Start the app
- Open camera with launchCamera
- taking photo
- touch ✔️ 
- crash

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 7.2.3
- React Native version: 0.73.11
- Platform: Android
- Development Operating System: MacOS (Apple Silicon)
- Dev tools: `buildToolsVersion = "34.0.0"`, `minSdkVersion = 24`, `compileSdkVersion = 34`, `targetSdkVersion = 34`, `ndkVersion = "25.1.8937393"`, `ENV['RCT_NEW_ARCH_ENABLED'] = '0'`

**Comment by plumest** [comment]
The issue was solved.

It error because of `SunmiScanModule` consume all the Activity without checking the eventCode.
I remove `react-native-sunmi-printer` an it work fine.

**Comment by aliyanlatif** [comment]
@plumest how did you got it resolved?

**Comment by Johnsonzhangc** [comment]
> The issue was solved.
> 
> It error because of `SunmiScanModule` consume all the Activity without checking the eventCode. I remove `react-native-sunmi-printer` an it work fine.

You are correct. Blocked the code in SunmiScanModule.java constructor also works for me.

**Comment by plumest** [comment]
> [@plumest](https://github.com/plumest) i am getting the same error, how did you got it resolved?

sorry for late reply 🙏🏻

You should grep onActivityResult error checking the libs that cause the error.
For me, it's SunmiScanModule. then searching in node_modules how it call onActivityResult and try to fix it.

I don't knows that is the latest version of `react-native-sunmi-printer` solve the issue?
but I did patches the lib myself. 

1. Create `patches/@heasy+react-native-sunmi-printer+1.8.4.patch` (check the version. for me it's 1.8.4).
2. I change the `START_SCAN` in `SunmiScanModule` to `0xBB01`.
3. `onActivityResult` adding the condition to check the `requestCode == START_SCAN`.

```
Binary files /dev/null and b/node_modules/@heasy/react-native-sunmi-printer/android/build/tmp/compileDebugJavaWithJavac/previous-compilation-data.bin differ
diff --git a/node_modules/@heasy/react-native-sunmi-printer/android/src/main/java/com/reactnativesunmiprinter/SunmiScanModule.java b/node_modules/@heasy/react-native-sunmi-printer/android/src/main/java/com/reactnativesunmiprinter/SunmiScanModule.java
index 9856b67..34ed940 100644
--- a/node_modules/@heasy/react-native-sunmi-printer/android/src/main/java/com/reactnativesunmiprinter/SunmiScanModule.java
+++ b/node_modules/@heasy/react-native-sunmi-printer/android/src/main/java/com/reactnativesunmiprinter/SunmiScanModule.java
@@ -23,7 +23,7 @@ import java.util.Iterator;
 
 public class SunmiScanModule extends ReactContextBaseJavaModule {
   private static ReactApplicationContext reactContext;
-  private static final int START_SCAN = 0x0000;
+  private static final int START_SCAN = 0xBB01;
   private static final String E_ACTIVITY_DOES_NOT_EXIST = "E_ACTIVITY_DOES_NOT_EXIST";
   private static final String E_FAILED_TO_SHOW_SCAN = "E_FAILED_TO_SHOW_SCAN";
   private static final String ACTION_DATA_CODE_RECEIVED = "com.sunmi.scanner.ACTION_DATA_CODE_RECEIVED";
@@ -48,7 +48,7 @@ public class SunmiScanModule extends ReactContextBaseJavaModule {
   private final ActivityEventListener mActivityEventListener = new BaseActivityEventListener() {
     @Override
     public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent intent) {
-      if (intent != null) {
+      if (intent != null && requestCode == START_SCAN) {
         Bundle bundle = intent.getExtras();
         ArrayList<HashMap<String, String>> result = (ArrayList<HashMap<String, String>>) bundle.getSerializable("data");
         if (null != result) {
```
